## Exercise on wine dataset


Let's start off by following the general workflow that we use when moving data into a DataFrame: 

    * Importing Pandas
    * Reading data into the DataFrame
    * Getting a general sense of the data

So, in terms of what you should do for this part...

1. Select the first 10 rows of the `chlorides` column. 
2. Select the last 10 rows of the `chlorides` column. 
3. Select columns `chlorides` **and** `density`. 
4. Select all rows where the `chlorides` value is less than 0.10. 
5. Now select all the rows where the `chlorides` value is greater than the column's mean (try **not** to use a hard-coded value for the mean, but instead a method).
6. Select all those rows where the `pH` is greater than 3.0 and less than 3.5. Further filter the results from 6 to grab only those rows that have a `residual sugar` less than 2.0. 

If you'd like some extra practice, try answering each of the questions in more than one way (because remember, we can often select data in a couple of different ways). Selecting is the same as displaying on the screen in this context.

In [1]:
# This file was edited for the GitHub exercises

# this file was edited differently and pushed to featureB
# this file was edited for the first time for the rebase-exercise branch

In [20]:
import pandas as pd
df_wine_quality.shape

(1599, 12)

In [3]:
df_wine_quality = pd.read_csv('../data/winequality-red.csv', sep=";")
df_wine_quality

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5
3,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6
4,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
...,...,...,...,...,...,...,...,...,...,...,...,...
1594,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5
1595,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,6
1596,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6
1597,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5
1598,6.0,0.310,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0,6

In [7]:
#1. Select the first 10 rows of the `chlorides` column. 
df_wine_quality.iloc[:10]['chlorides']
#2. Select the last 10 rows of the `chlorides` column. 
df_wine_quality.iloc[-10:]['chlorides']

1589    0.073
1590    0.077
1591    0.089
1592    0.076
1593    0.068
1594    0.090
1595    0.062
1596    0.076
1597    0.075
1598    0.067
Name: chlorides, dtype: float64

In [8]:
#3. Select columns `chlorides` and `density`. 
df_wine_quality[['chlorides', 'density']]

      chlorides  density
0         0.076  0.99780
1         0.098  0.99680
2         0.092  0.99700
3         0.075  0.99800
4         0.076  0.99780
...         ...      ...
1594      0.090  0.99490
1595      0.062  0.99512
1596      0.076  0.99574
1597      0.075  0.99547
1598      0.067  0.99549

[1599 rows x 2 columns]

In [12]:
#4. Select all rows where the `chlorides` value is less than 0.10.
chloride_low = df_wine_quality['chlorides'] < .10
chloride_low

0       True
1       True
2       True
3       True
4       True
        ...
1594    True
1595    True
1596    True
1597    True
1598    True
Name: chlorides, Length: 1599, dtype: bool

In [19]:
#5. Now select all the rows where the `chlorides` value is greater than the column's mean
#(try not to use a hard-coded value for the mean, but instead a method.)
wine_chl_mean = df_wine_quality['chlorides'].mean()
chloride_above_mean = df_wine_quality[df_wine_quality['chlorides'] > wine_chl_mean]
chloride_above_mean

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5
10,6.7,0.580,0.08,1.8,0.097,15.0,65.0,0.99590,3.28,0.54,9.2,5
12,5.6,0.615,0.00,1.6,0.089,16.0,59.0,0.99430,3.58,0.52,9.9,5
13,7.8,0.610,0.29,1.6,0.114,9.0,29.0,0.99740,3.26,1.56,9.1,5
...,...,...,...,...,...,...,...,...,...,...,...,...
1558,6.9,0.630,0.33,6.7,0.235,66.0,115.0,0.99787,3.22,0.56,9.5,5
1570,6.4,0.360,0.53,2.2,0.230,19.0,35.0,0.99340,3.37,0.93,12.4,6
1578,6.8,0.670,0.15,1.8,0.118,13.0,20.0,0.99540,3.42,0.67,11.3,6
1591,5.4,0.740,0.09,1.7,0.089,16.0,26.0,0.99402,3.67,0.56,11.6,6
1594,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5

In [ ]:
#6. Select all those rows where the `pH` is greater than 3.0 and less than 3.5. 
df_wine_quality_ph_range = df_wine_quality[(df_wine_quality['pH'] > 3.0) & (df_wine_quality['pH'] < 3.5)] 
df_wine_quality_ph_range

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6
6,7.9,0.60,0.06,1.6,0.069,15.0,59.0,0.99640,3.30,0.46,9.4,5
7,7.3,0.65,0.00,1.2,0.065,15.0,21.0,0.99460,3.39,0.47,10.0,7
...,...,...,...,...,...,...,...,...,...,...,...,...
1592,6.3,0.51,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6
1593,6.8,0.62,0.08,1.9,0.068,28.0,38.0,0.99651,3.42,0.82,9.5,6
1594,6.2,0.60,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5
1596,6.3,0.51,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6
1598,6.0,0.31,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0,6

In [27]:
#7. Further filter the results from 6 to grab only those rows that have a `residual sugar` less than 2.0.
#Tip: Use backticks (``) to mask column names with spaces in query string.
df_wine_quality_ph_range_low_sugar = df_wine_quality[(df_wine_quality['pH'] > 3.0) & (df_wine_quality['pH'] < 3.5) & (df_wine_quality['residual sugar'] < 2.0)] 
df_wine_quality_ph_range_low_sugar

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6
6,7.9,0.60,0.06,1.6,0.069,15.0,59.0,0.99640,3.30,0.46,9.4,5
7,7.3,0.65,0.00,1.2,0.065,15.0,21.0,0.99460,3.39,0.47,10.0,7
10,6.7,0.58,0.08,1.8,0.097,15.0,65.0,0.99590,3.28,0.54,9.2,5
13,7.8,0.61,0.29,1.6,0.114,9.0,29.0,0.99740,3.26,1.56,9.1,5
...,...,...,...,...,...,...,...,...,...,...,...,...
1569,6.2,0.51,0.14,1.9,0.056,15.0,34.0,0.99396,3.48,0.57,11.5,6
1576,8.0,0.30,0.63,1.6,0.081,16.0,29.0,0.99588,3.30,0.78,10.8,6
1578,6.8,0.67,0.15,1.8,0.118,13.0,20.0,0.99540,3.42,0.67,11.3,6
1590,6.3,0.55,0.15,1.8,0.077,26.0,35.0,0.99314,3.32,0.82,11.6,6
1593,6.8,0.62,0.08,1.9,0.068,28.0,38.0,0.99651,3.42,0.82,9.5,6

## Exercise on iris dataset

![IRIS, https://github.com/simonava5/fishers-iris-data](images/iris.png)

After the notebook with a lot of new input, let's start applying it totally by yourselves. 
For this purpose we will use one of the most standard real-life datasets: It's called Iris Dataset, and is all about the plant iris. Let's learn a little bit more about the dataset by taking a closer look at it.

In [28]:
import pandas as pd

In [38]:
# load the data
df_iris = pd.read_csv('../data/iris.csv')
df_iris
df_iris.shape

(150, 6)

1. Let us first have a look at the head of the table, maybe also on the last 10 rows...

In [37]:
# Your playground
df_iris.head(10)
df_iris.iloc[-10:]

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
140,141,6.7,3.1,5.6,2.4,Iris-virginica
141,142,6.9,3.1,5.1,2.3,Iris-virginica
142,143,5.8,2.7,5.1,1.9,Iris-virginica
143,144,6.8,3.2,5.9,2.3,Iris-virginica
144,145,6.7,3.3,5.7,2.5,Iris-virginica
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

2. How many irises are the data set?

In [42]:
df_iris["Species"].value_counts()

Species
Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: count, dtype: int64

3. Calculate the basic descriptive statistics for all columns of the iris data set using a single command.

In [43]:
df_iris.describe

<bound method NDFrame.describe of       Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2
1      2            4.9           3.0            1.4           0.2
2      3            4.7           3.2            1.3           0.2
3      4            4.6           3.1            1.5           0.2
4      5            5.0           3.6            1.4           0.2
..   ...            ...           ...            ...           ...
145  146            6.7           3.0            5.2           2.3
146  147            6.3           2.5            5.0           1.9
147  148            6.5           3.0            5.2           2.0
148  149            6.2           3.4            5.4           2.3
149  150            5.9           3.0            5.1           1.8

            Species
0       Iris-setosa
1       Iris-setosa
2       Iris-setosa
3       Iris-setosa
4       Iris-setosa
..              ...
145  Iris-virginica
146  Iris-virginica
147  Iris-virginica
148  Iris-virginica
149  Iris-virginica

[150 rows x 6 columns]>

4. Add the sum of the sepal width and length as a new column to your data frame.

In [45]:
df_iris['sepal_space'] = df_iris['SepalLengthCm'] * df_iris['SepalWidthCm']
df_iris.head()

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species,sepal_space
0,1,5.1,3.5,1.4,0.2,Iris-setosa,17.85
1,2,4.9,3.0,1.4,0.2,Iris-setosa,14.70
2,3,4.7,3.2,1.3,0.2,Iris-setosa,15.04
3,4,4.6,3.1,1.5,0.2,Iris-setosa,14.26
4,5,5.0,3.6,1.4,0.2,Iris-setosa,18.00

5. Create a new column with a rough estimate of petal area by multiplying petal length and width together.

In [50]:
# Your playground
df_iris['petal_space'] = df_iris['PetalLengthCm'] * df_iris['PetalLengthCm']
df_iris.head()

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species,sepal_space,petal_space
0,1,5.1,3.5,1.4,0.2,Iris-setosa,17.85,1.96
1,2,4.9,3.0,1.4,0.2,Iris-setosa,14.70,1.96
2,3,4.7,3.2,1.3,0.2,Iris-setosa,15.04,1.69
3,4,4.6,3.1,1.5,0.2,Iris-setosa,14.26,2.25
4,5,5.0,3.6,1.4,0.2,Iris-setosa,18.00,1.96

6. Create a new dataframe with petal areas greater than $1cm^2$.

In [53]:
df_big_petal_space = df_iris[(df_iris['petal_space'] > 1)]
df_big_petal_space

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species,sepal_space,petal_space
0,1,5.1,3.5,1.4,0.2,Iris-setosa,17.85,1.96
1,2,4.9,3.0,1.4,0.2,Iris-setosa,14.70,1.96
2,3,4.7,3.2,1.3,0.2,Iris-setosa,15.04,1.69
3,4,4.6,3.1,1.5,0.2,Iris-setosa,14.26,2.25
4,5,5.0,3.6,1.4,0.2,Iris-setosa,18.00,1.96
...,...,...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica,20.10,27.04
146,147,6.3,2.5,5.0,1.9,Iris-virginica,15.75,25.00
147,148,6.5,3.0,5.2,2.0,Iris-virginica,19.50,27.04
148,149,6.2,3.4,5.4,2.3,Iris-virginica,21.08,29.16
149,150,5.9,3.0,5.1,1.8,Iris-virginica,17.70,26.01

7. Using the original unfiltered dataframe, create 3 new dataframes, each containing only irises of each a single species 'Iris-setosa', 'Iris-versicolor' or 'Iris-virginica'.

In [55]:
df_iris_setosa = df_iris[df_iris['Species'] == 'Iris-setosa']
df_iris_versicolor = df_iris[df_iris['Species'] == 'Iris-versicolor']
df_iris_virginica = df_iris[df_iris['Species'] == 'Iris-virginica']
# Your playground